[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TOMLConfig = "e5d2e90d-178f-44ca-b451-862405e5e996"

[sources]
TOMLConfig = {path = ".."}

[compat]
Documenter = "0.27, 1"
TOMLConfig = "0.1.0"
